# Generated by Django 5.2.7 on 2025-11-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_room_rename_body_message_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
