# Generated by Django 5.2.8 on 2025-11-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_room_name_room_first_user_room_second_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='first_user',
            new_name='other_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='second_user',
        ),
    ]
