# Generated by Django 5.2.8 on 2025-11-09 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_description'),
        ('users', '0007_rename_first_user_room_other_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='other_user',
            new_name='applicant',
        ),
        migrations.AddField(
            model_name='room',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
