# Generated by Django 5.2.8 on 2025-11-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_other_user_room_applicant_room_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='room',
            name='company',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
