# Generated by Django 5.2.8 on 2025-11-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
