# Generated by Django 5.2.7 on 2025-12-30 14:24

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='description')),
                ('experience', models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Lead', 'Lead')], default='Junior', max_length=50)),
                ('category', models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Arts', 'Arts'), ('Business', 'Business'), ('Communications', 'Communications'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Information technology', 'Information technology'), ('Law', 'Law'), ('Sales and Marketing', 'Sales and Marketing'), ('Science', 'Science'), ('Transportation', 'Transportation')], default='Uncategorized', max_length=50)),
                ('mode', models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default='Full-time', max_length=50)),
                ('model', models.CharField(choices=[('Onsite', 'Onsite'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Onsite', max_length=50)),
                ('salary', models.PositiveBigIntegerField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('tags', models.ManyToManyField(blank=True, to='iamavailable.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('suitability', models.TextField()),
                ('resume', models.URLField(max_length=300)),
                ('expected_salary', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('Undecided', 'Undecided'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Undecided', max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iamavailable.job')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iamavailable.job')),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iamavailable.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
