# Generated by Django 5.2.7 on 2025-12-29 14:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
