# Generated by Django 5.2.7 on 2025-10-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
