# Generated by Django 5.2.7 on 2025-11-26 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iamavailable.job'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
