# Generated by Django 5.2.7 on 2025-10-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0002_jobs_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.PositiveBigIntegerField(),
        ),
    ]
