# Generated by Django 5.2.7 on 2025-11-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0002_alter_saved_job_alter_saved_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='expected_salary',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='suitability',
            field=models.TextField(blank=True, null=True),
        ),
    ]
