# Generated by Django 5.2.7 on 2025-12-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0002_alter_notification_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
