# Generated by Django 5.2.7 on 2025-10-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0003_alter_jobs_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
