# Generated by Django 5.2.7 on 2025-11-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0003_application_expected_salary_application_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='expected_salary',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='suitability',
            field=models.TextField(),
        ),
    ]
