# Generated by Django 5.2.7 on 2025-10-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0004_jobs_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='mode',
            field=models.CharField(choices=[('part_time', 'Part-time'), ('full_time', 'Full-time')], default='Full-time', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
