# Generated by Django 5.2.7 on 2026-01-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0004_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
    ]
