# Generated by Django 5.2.7 on 2025-10-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0005_jobs_mode_alter_jobs_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='mode',
            field=models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default='Full-time', max_length=50),
        ),
    ]
