# Generated by Django 5.2.7 on 2025-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0006_alter_jobs_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
