# Generated by Django 5.2.7 on 2025-12-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_new',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Undecided', 'Undecided'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Undecided', max_length=50),
        ),
    ]
