# Generated by Django 5.2.7 on 2025-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0007_jobs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
