# Generated by Django 5.2.7 on 2025-10-16 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0009_jobs_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mode', models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time')], default='Full-time', max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.PositiveBigIntegerField()),
                ('number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
