# Generated by Django 5.2.7 on 2025-12-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0009_remove_job_category_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Arts', 'Arts'), ('Business', 'Business'), ('Communications', 'Communications'), ('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Information technology', 'Information technology'), ('Law', 'Law'), ('Sales and Marketing', 'Sales and Marketing'), ('Science', 'Science'), ('Transportation', 'Transportation')], default='Uncategorized', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
