# Generated by Django 5.2.7 on 2025-10-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0011_tag_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Lead', 'Lead')], default='Junior', max_length=50),
        ),
    ]
