# Generated by Django 5.2.7 on 2025-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0013_job_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='job',
            name='model',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='Onsite', max_length=50),
        ),
    ]
