# Generated by Django 5.2.7 on 2025-10-29 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('iamavailable', '0014_alter_tag_options_job_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_manual',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
