# Generated by Django 5.2.7 on 2025-10-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0015_job_company_manual_alter_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_manual',
        ),
    ]
