# Generated by Django 5.2.7 on 2025-10-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0017_alter_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
    ]
