# Generated by Django 5.2.7 on 2025-11-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamavailable', '0019_saved_application'),
        ('users', '0006_remove_message_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iamavailable.job'),
        ),
        migrations.AddField(
            model_name='saved',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
